---
abstract: 'Use featured keywords on older Perls'
author:
  - 'Brad Gilbert <b2gills@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Featured
no_index:
  directory:
    - t
    - xt
provides:
  Featured:
    file: lib/Featured.pm
    version: 0.000002
recommends:
  Package::Stash: 0.14
  Package::Stash::XS: 0
requires:
  Package::Stash: 0
  Scalar::Util: 0
  perl: 5.006
resources:
  bugtracker: http://github.com/b2gills/Featured/issues
  repository: git://github.com/b2gills/Featured.git
version: 0.000002
